export const NAVBARCONSTANT = [
  {
    id: "ayala-greenfield-estate",
    name: "Ayala Greenfield Estate",
    images: [
      { src: "/images/AGE1.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE2.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE3.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE4.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE5.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE6.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE7.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE8.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE9.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE10.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE11.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE12.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE13.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE14.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE15.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE16.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE17.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE18.webp", alt: "Ayala-Greenfield" },
      { src: "/images/AGE19.webp", alt: "Ayala-Greenfield" },
    ],
    logo: "age-logo.webp",
    title: "Ayala Greenfield Estates",
    about:
      "Lush landscapes and rolling terrain—in Ayala Greenfield Estates, the calm and constancy of nature belies life’s dynamism. Enveloped by vistas of Mt. Makiling and Laguna de Bay, an idyllic, mountainside living experience unfolds. Natural amenities and a dedicated country club capture a living portrait of sweeping views. Fairways, park, mountain, lake—your home pulls into focus nature at its most astonishing.",
    description:
      "Ayala Greenfield Estates is accessible via South Luzon Expressway (SLEX) through the Batangas Exit, a quick drive from NUVALI, and only 30 minutes by car from Alabang. The first Ayala Land Premier development in Calamba, Laguna, spanning 350 hectares, features distinct residential enclaves complemented by parks, open spaces, and unparalleled amenities, surrounding residents with a world of nature.",
    map: "age-map.webp",
    landArea: "350 hectares",
    numberOfPhases: "9 phases",
    peakElevation: "315 meters above sea level",
    location: "Calamba, Laguna, Philippines",
  },
  {
    id: "arcilo",
    name: "Arcilo Nuvali",
    images: [
      { src: "/images/arcilo1.webp", alt: "Arcilo-Nuvali" },
      { src: "/images/arcilo2.webp", alt: "Arcilo-Nuvali" },
      { src: "/images/arcilo3.webp", alt: "Arcilo-Nuvali" },
    ],
    logo: "arcilo-logo.webp",
    title: "Arcilo Nuvali",
    about:
      "Surrounded by a lush, natural landscape, this distinctive neighborhood is embraced by large acacia trees, creating a unique setting for families to take root and thrive. Discover a new enclave where dense foliage and overarching canopies provide natural shade and a distinct charm for residents. Ayala Land Premier welcomes you to its newest address in the growing NUVALI estate.",
    description:
      "Ayala Land Premier’s tenth neighborhood in NUVALI is located in the southern expanse of the estate along Evoliving Parkway. It is easily accessible to the main road of Nuvali Boulevard and close to all the conveniences and support establishments within the estate. Arcilo is surrounded by existing premier villages and bordered by the Cauang-Cauang River to the west, providing natural barriers and heightened exclusivity.",
    map: "arcilo-map.webp",
    landArea: "30 hectares",
    numberOfPhases: "1 phase",
    peakElevation: "145 – 175 meters above mean sea level",
    location: "Nuvali, Santa Rosa Laguna, Philippines",
    developmentSummary: {
      openSpaces: "50%",
      numberOfLots: "273 lots",
      density: "9 lots per hectare",
      lotSizeRange: "400 – 1,923 square meters",
      terrain: "Relatively flat",
    },
  },
  {
    id: "ciela-aera-heights",
    name: "Ciela at Aéra Heights",
    images: [
      { src: "/images/cah1.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah2.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah3.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah4.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah5.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah6.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah7.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah8.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah9.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah10.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah11.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah12.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah13.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah14.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah15.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah16.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah17.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah18.webp", alt: "Ciela-at-Aéra-Heights" },
      { src: "/images/cah19.webp", alt: "Ciela-at-Aéra-Heights" },
    ],
    logo: "cah-logo.webp",
    title: "Ciela at Aéra Heights",
    about:
      "Ciela is the pioneer residential community in Aéra Heights, the elevated residential district of the estate. Ciela rests on a natural bluff, enveloped by waterways, ridges, and lush vegetation, providing a distinctive living experience enriched by the landscape. Unfolding on 165 hectares of undulating, ridgeside terrain, the village dedicates close to 70% to open spaces. A verdant atmosphere imbues living spaces with the vibrancy of nature, from earth to sky.",
    description:
      "Enveloped in greenery, heightened elevations, and luminous, wide-open views of city and sky, with flowing waterways throughout the undulating terrain. In Carmona, Cavite, Ayala Land reveals AÉRA, a destination communing nature, people, and spaces in one dynamic, strategically connected, and accessible estate. A landscape primed to nurture overall growth and well-being. AÉRA is a contemporary estate spanning close to a thousand hectares, converging a commercial district, expansive residential environments, and recreational destinations into a natural, elevated landscape.",
    map: "cah-map.webp",
    landArea: "67 hectares",
    totalLandArea:
      "241 hectares (Phase 1: 67 hectares, Phase 2 Tranche One: 74 hectares, remaining phases: 100 hectares)",
    peakElevation: "172 - 217 meters above mean sea level",
    location: "Carmona, Cavite, Philippines",
    developmentSummary: [
      {
        phase: "Phase 1",
        landArea: "67 hectares",
        openSpaces: "70%",
        numberOfLots: "300",
        density: "4 lots per hectare",
        lotSizeRange: "446-1,446 square meters",
        elevation: "172-217 meters above mean sea level",
        terrain: "Rolling",
      },
      {
        phase: "Phase 2 Tranche One",
        landArea: "74 hectares",
        openSpaces: "70%",
        numberOfLots: "144",
        density: "4 lots per hectare",
        lotSizeRange: "500-1,987 square meters",
        elevation: "130-185 meters above mean sea level",
        terrain: "Rolling",
      },
    ],
  },
  {
    id: "lanewood-hills",
    name: "Lanewood Hills at Southmont",
    images: [
      { src: "/images/lh1.webp", alt: "lanewood-hills" },
      { src: "/images/lh2.webp", alt: "lanewood-hills" },
      { src: "/images/lh3.webp", alt: "lanewood-hills" },
      { src: "/images/lh4.webp", alt: "lanewood-hills" },
    ],
    logo: "lh-logo.webp",
    title: "Lanewood Hills at Southmont",
    about:
      "Undulating landscapes and greenery intertwine with residential enclaves in Ayala Land Premier’s newest neighborhood in the south. By preserving the natural features of the land, sprawling greenways will remain untouched, stretching throughout the development. Configured along ridges, homes overlook views of lush treetops, with everyday life imbued with the sights and sounds of nature.",
    description:
      "Located in Silang, Cavite, Lanewood Hills at Southmont is nestled within a community jointly developed by Ayala Land and Cathay Land. Its unique location puts it in proximity to the vibrant NUVALI estate and the leisure destinations of Tagaytay.",
    map: "lh-map.webp",
    landArea: "57 hectares",
    peakElevation: "193 – 265 meters above mean sea level",
    location: "Silang, Cavite, Philippines",
    developmentSummary: {
      openSpaces: "62%",
      numberOfLots: "362 lots",
      density: "6 lots per hectare",
      lotSizeRange: "500 – 962 square meters",
      averageLotSize: "593 square meters",
      terrain: "Rolling",
    },
  },
  {
    id: "miravera-altaraza",
    name: "Miravera at Altaraza",
    images: [
      { src: "/images/ma1.webp", alt: "Miravera-at-Altaraza" },
      { src: "/images/ma2.webp", alt: "Miravera-at-Altaraza" },
      { src: "/images/ma3.webp", alt: "Miravera-at-Altaraza" },
      { src: "/images/ma4.webp", alt: "Miravera-at-Altaraza" },
    ],
    logo: "ma-logo.webp",
    title: "Miravera at Altaraza",
    about:
      "Altaraza transforms potential into the next growth center in northeastern Manila. Converging urban energy with nature in Bulacan, a 40 hectare Master-planed Estate with a 600 hectare expansion area is nestled within a wide range of residential and commercial spaces set against a captivating backdrop of the Sierra Madre mountains.",
    description:
      "The estate is conveniently located just outside Metro Manila at the boundary of Caloocan and Bulacan. It is highly accessible through a direct connection to Quirino Highway along with planned government infrastructure projects such as MRT-7 and Bulacan International Airport.",
    map: "ma-map.webp",
    landArea: "29 hectares",
    numberOfPhases: "1 phase",
    peakElevation: "70 - 130 meters above mean sea level",
    location: "San Jose del Monte, Bulacan, Philippines",
    developmentSummary: {
      openSpaces: "57%",
      numberOfLots: "125 lots",
      density: "Approx. 4 lots per hectare",
      lotSizeRange: "425 – 5,000 square meters",
      terrain: "Rolling",
    },
  },
  {
    id: "the-courtyards-vermosa",
    name: "The Courtyards at Vermosa",
    images: [
      { src: "/images/tcv1.webp", alt: "The-Courtyard-at-Vermosa" },
      { src: "/images/tcv2.webp", alt: "The-Courtyard-at-Vermosa" },
      { src: "/images/tcv3.webp", alt: "The-Courtyard-at-Vermosa" },
      { src: "/images/tcv4.webp", alt: "The-Courtyard-at-Vermosa" },
    ],
    logo: "tcv-logo.webp",
    title: "The Courtyards at Vermosa",
    about:
      "Extending growth and dynamism in the South, a thriving estate spurs active and living wellness with distinct recreation and lifestyle destinations, interconnected verdant parks, and outdoor retail spaces. The Courtyards opens a private sanctuary celebrating a magnified experience of living with an abundance of possibilities and conveniences.",
    description:
      "An emerging destination for active lifestyles unfolds an expanse of venues centered on sports and fitness. Just a few minutes away from Alabang and Makati City, The Courtyards offers a bespoke slice of community life accessible via SLEX through the Muntinlupa-Cavite Expressway (MCX) and Aguinaldo Highway. Urban conveniences in an astonishing suburban setting—Ayala Land Premier invites you to a life enriched by home and community.",
    map: "tcv-map.webp",
    landArea: "125 hectares",
    numberOfPhases: "1 phase",
    peakElevation: "40 – 80 meters above mean sea level",
    location: "Dasmariñas and Imus, Cavite, Philippines",
    developmentSummary: {
      numberOfLots: "904 lots",
      density: "7 lots per hectare",
      lotSizeRange: "470 – 1,947 square meters",
    },
  },
  {
    id: "arbor-lanes",
    name: "Arbor Lanes, Arca South",
    images: [
      { src: "/images/al1.webp", alt: "Arbor-Lanes" },
      { src: "/images/al2.webp", alt: "Arbor-Lanes" },
      { src: "/images/al3.webp", alt: "Arbor-Lanes" },
      { src: "/images/al4.webp", alt: "Arbor-Lanes" },
      { src: "/images/al5.webp", alt: "Arbor-Lanes" },
      { src: "/images/al6.webp", alt: "Arbor-Lanes" },
      { src: "/images/al7.webp", alt: "Arbor-Lanes" },
      { src: "/images/al8.webp", alt: "Arbor-Lanes" },
      { src: "/images/al9.webp", alt: "Arbor-Lanes" },
      { src: "/images/al10.webp", alt: "Arbor-Lanes" },
      { src: "/images/al11.webp", alt: "Arbor-Lanes" },
      { src: "/images/al12.webp", alt: "Arbor-Lanes" },
      { src: "/images/al13.webp", alt: "Arbor-Lanes" },
      { src: "/images/al14.webp", alt: "Arbor-Lanes" },
      { src: "/images/al15.webp", alt: "Arbor-Lanes" },
    ],

    logo: "al-logo.webp",
    title: "Arbor Lanes, Arca South",
    about:
      "Arbor Lanes, Arca South intertwines greenery and architecture in a vast 3.48-hectare development, complemented by commercial buildings to its north. Various configurations reveal landscapes and garden views, where a natural breeze and minimized sun exposure create a pleasant microclimate through a distinctive building orientation. Verdant spaces refresh urban lifestyles throughout the development. Four amenity spines create a communal atmosphere enlivened by vibrant foliage—expansive lawns, tree wells, outdoor lounges, pools, garden terraces, and halls—environments weaving together home and nature.",
    description:
      "Arbor Lanes, Arca South is located at ARCA South, a 74-hectare, large-scale, master-planned, mixed-use, sustainable estate by Ayala Land in Taguig. Opening the gateway to the South, this emerging central business district offers prime accessibility through South Luzon Expressway (SLEX), C-5, and future connections to the Skyway. Workspaces, residences, parks, retail, and entertainment destinations harmonize, creating a contemporary community for business and lifestyles.",
    map: "al-map.webp",
    location: "Arca South, Taguig City, Philippines",
    developmentSummary: {
      olive: {
        floors: "17",
        units: "216",
        unitSizeRange: "68—286 sqm",
      },
      jade: {
        floors: "17",
        units: "263",
        unitSizeRange: "86—313 sqm",
      },
    },
  },
  {
    id: "gardencourt-residences",
    name: "Gardencourt Residences, Arca South",
    images: [
      { src: "/images/gr1.webp", alt: "gardencourt-residences" },
      { src: "/images/gr2.webp", alt: "gardencourt-residences" },
      { src: "/images/gr3.webp", alt: "gardencourt-residences" },
      { src: "/images/gr4.webp", alt: "gardencourt-residences" },
      { src: "/images/gr5.webp", alt: "gardencourt-residences" },
      { src: "/images/gr6.webp", alt: "gardencourt-residences" },
      { src: "/images/gr7.webp", alt: "gardencourt-residences" },
      { src: "/images/gr8.webp", alt: "gardencourt-residences" },
      { src: "/images/gr9.webp", alt: "gardencourt-residences" },
      { src: "/images/gr10.webp", alt: "gardencourt-residences" },
      { src: "/images/gr11.webp", alt: "gardencourt-residences" },
      { src: "/images/gr12.webp", alt: "gardencourt-residences" },
      { src: "/images/gr13.webp", alt: "gardencourt-residences" },
      { src: "/images/gr14.webp", alt: "gardencourt-residences" },
      { src: "/images/gr15.webp", alt: "gardencourt-residences" },
    ],
    logo: "gr-logo.webp",
    title: "Gardencourt Residences, Arca South",
    about:
      "Gardencourt Residences, Arca South is a two-hectare parkside community of five cascading residential towers enveloping the expansive Gardencourt—a 6,000-square meter courtyard featuring open spaces, pockets of green, shared amenities, and settings for relaxation and play, connection and quiet. Maximized ceiling heights, expansive windows, and balconies open homes to abundant natural light, illuminating lifestyles of distinction.",
    description:
      "The development is located at ARCA South, a 74-hectare, large-scale, master-planned, mixed-use, sustainable estate by Ayala Land in Taguig. An emerging central business district with prime accessibility through South Luzon Expressway (SLEX), C-5, and future connections to the Skyway. A dynamic community for contemporary business and lifestyles.",
    map: "gr-map.webp",
    location: "Arca South, Taguig City, Philippines",
    developmentSummary: {
      molave: {
        floors: "16/19",
        totalNoOfUnits: "134 units",
        density: "Up to 9 units per floor",
        unitConfigurations: "1BR — 3BR",
        unitSizeRange: "69—259 sqm",
      },
      narra: {
        floors: "22",
        totalNoOfUnits: "230 units",
        density: "Up to 12 units per floor",
        unitConfigurations: "1BR — 2BR",
        unitSizeRange: "69—259 sqm",
      },
    },
  },
  {
    id: "parklinks-north-south-towers",
    name: "Parklinks North and South Towers",
    images: [
      { src: "/images/pkl1.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl2.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl3.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl4.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl5.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl6.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl7.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl8.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl9.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl10.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl11.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl12.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl13.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl14.webp", alt: "parklinks-north-south-towers" },
      { src: "/images/pkl15.webp", alt: "parklinks-north-south-towers" },
    ],
    logo: "pkl-logo.webp",
    title: "Parklinks North and South Towers",
    about:
      "Ayala Land, in partnership with Eton Properties, continues a pioneering heritage, setting the standard for master-planned, large-scale, mixed-use, and sustainable developments with the greenest urban estate in Quezon City and Pasig—Parklinks. Sprawling parks extend throughout the entire estate, creating a highly integrated community enhanced by green spaces. Ayala Land Premier reveals a panorama of living, esteemed addresses within a dynamic growth corridor with Parklinks North and South Towers.",
    description:
      "Located at the intersection of Quezon City and Pasig, Parklinks is easily accessible via C-5, Ortigas Avenue, and Amang Rodriguez Avenue, connecting the estate to surrounding key commercial, retail, and institutional developments, including the country’s esteemed schools along Katipunan. The 35-hectare sustainable masterplan dedicates 50% to a network of dynamic parks and refreshing green spaces, woven into an array of retail and leisure spots, offices, and living spaces. Designed for high pedestrian mobility, parks are within a five-minute walk from any point in the estate.",
    map: "pkl-map.webp",
    landArea: "4,145 sqm (North Tower), 4,002 sqm (South Tower)",
    location: "Quezon City and Pasig City, Philippines",
    developmentSummary: {
      northTower: {
        landArea: "4,145 sqm",
        floors: "55",
        units: "280",
        density: "4—8 units per floor",
        unitSizeRange: "70—306 sqm",
      },
      southTower: {
        landArea: "4,002 sqm",
        floors: "55",
        units: "313",
        density: "4—9 units per floor",
        unitSizeRange: "70—286 sqm",
      },
    },
  },
  {
    id: "residences-azuela-cove",
    name: "The Residences at Azuela Cove",
    images: [
      { src: "/images/trac1.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac2.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac3.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac4.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac5.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac6.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac7.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac8.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac9.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac10.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac11.webp", alt: "residences-azuela-cove" },
      { src: "/images/trac12.webp", alt: "residences-azuela-cove" },
    ],
    logo: "trac-logo.webp",
    title: "The Residences at Azuela Cove",
    about:
      "The Alcantara Group—a shared vision with Ayala Land—brings together Mindanao’s pioneer in infrastructure, agri-business, and property development. Azuela Cove is a prime mixed-use, master-planned development in Davao. It is a vibrant destination where people and pursuits converge, offering a dynamic hub with undulating spaces for leisure, activity, recreation, entertainment, business, and home. Presenting a new wave of living in Davao’s premier waterside community. The Residences at Azuela Cove is a two-tower, low-density, all-suite development where every residential space faces seaward. Spaces for activity and convergence channel radiance and effortlessness into everyday living. A spectrum of contemporary amenities and facilities complements the outstanding blue expanse, elevating lifestyles by the sea.",
    description:
      "Located at the intersection of J.P. Laurel Avenue and R. Castillo Street, Azuela Cove is Ayala Land’s first waterside, mixed-use estate in the region. This 25-hectare business and residential development at Kilometer Seven Lanang faces Samal Island and Davao Gulf. Forty percent of the estate will be dedicated to greens and open spaces, with a Central Park serving as a sprawling green spine that connects all parts of Azuela Cove to the seaside Esplanade, its dynamic centerpiece, which unfolds vistas of Davao Gulf and Samal Island.",
    map: "trac-map.webp",
    landArea: "10,019 sqm",
    numberOfPhases: "2 phases",
    location: "Davao City, Philippines",
    developmentSummary: {
      landArea: "10,019 sqm",
      numberOfFloors: "NORTH TOWER 21, SOUTH TOWER 22",
      numberOfUnits: "NORTH TOWER 70, SOUTH TOWER 77",
      unitSizeRange: "500—597 sqm",
      density: "2—4 units per floor",
      views: "Davao Gulf, Samal Island, Azuela Cove, Davao City",
    },
  },
  {
    id: "one-vertis-plaza",
    name: "One Vertis Plaza",
    images: [
      { src: "/images/ovp1.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp2.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp3.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp4.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp5.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp6.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp7.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp8.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp9.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp10.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp11.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp12.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp13.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp14.webp", alt: "one-vertis-plaza" },
      { src: "/images/ovp15.webp", alt: "one-vertis-plaza" },
    ],
    logo: "ovp-logo.webp",
    title: "One Vertis Plaza",
    about:
      "One Vertis Plaza signals a new branch in Ayala Land Premier’s evolution, presenting distinctive professional environments in Quezon City. Prime workspaces, directly accessible to the two-hectare Vertis North Gardens, offer unobstructed views of opportunities ahead. This dynamic corporate address is designed for business and investment, helping define your measure of success.",
    description:
      "Located at the regional gateway to the North, serving as the main transportation hub between Metro Manila and Northern Luzon, One Vertis Plaza is accessible via major road networks including EDSA, Mindanao Avenue, and Quezon Avenue. This prime location opens up a dynamic range of opportunities for business, leisure, and living, accelerating growth for both emerging and established enterprises. Vertis North is a 45-hectare, mixed-use estate developed by Ayala Land in partnership with the National Housing Authority (NHA). The estate is a dynamic community seamlessly fusing natural details with elements of contemporary living in one destination.",
    map: "ovp-map.webp",
    landArea: "6,060 sqm",
    location: "Quezon City, Philippines",
    developmentSummary: {
      developmentType: "Premium LEED Registered Building",
      floorAreaRatio: "12.9",
      numberOfOfficeUnits: "372",
      numberOfOfficeFloors: {
        executiveZone: "5 storeys",
        highZone: "13 storeys",
        midZone: "20 storeys",
      },
      numberOfOfficeUnitsPerFloor: "8 to 10 units",
      buildingHeight: "174.7 meters",
    },
  },
  {
    id: "anvaya-cove",
    name: "Anvaya Cove",
    images: [
      { src: "/images/ac1.webp", alt: "anvaya-cove" },
      { src: "/images/ac2.webp", alt: "anvaya-cove" },
      { src: "/images/ac3.webp", alt: "anvaya-cove" },
      { src: "/images/ac4.webp", alt: "anvaya-cove" },
      { src: "/images/ac5.webp", alt: "anvaya-cove" },
      { src: "/images/ac6.webp", alt: "anvaya-cove" },
      { src: "/images/ac7.webp", alt: "anvaya-cove" },
      { src: "/images/ac8.webp", alt: "anvaya-cove" },
      { src: "/images/ac9.webp", alt: "anvaya-cove" },
      { src: "/images/ac10.webp", alt: "anvaya-cove" },
    ],
    logo: "anvaya-logo.webp",
    title: "Anvaya Cove",
    about:
      "Presenting the excitement of a seaside resort and the tranquility of a mountain retreat, unique tropical features provide residents with the best that nature has to offer. A 620-hectare development designed for shared moments among family, Anvaya Cove offers endless opportunities to forge lifelong memories. A dynamic community nurturing family above everything else. With an array of amenities, services, events and activities, family ties flourish at Anvaya Cove.",
    features: [
      "Residential Neighborhoods",
      "Residential Condominium",
      "Golf & Sports Share",
      "Beach and Nature Club Shares",
    ],
    description: `Located in Morong, Bataan, Anvaya Cove is accessible via North Luzon Expressway (NLEX) through San Fernando Exit, Subic-Clark-Tarlac Expressway (SCTEX), and Angeles Exit. 
    It is approximately 2.5 hours from Manila by car, only 20 minutes away from the Subic Bay Freeport Zone, offering an accessible escape from the city. 
    Anvaya Cove offers:
    ● Residential Neighborhoods
    ● Residential Condominium
    ● Golf & Sports Share
    ● Beach and Nature Club Shares.`,
    map: "ac-map.webp",
    landArea: "620 hectares",
    peakElevation: "130 meters above sea level",
    location: "Morong, Bataan",
    developmentSummary: {
      coastline: "3.5 kilometers",
      density: "6 to 13 lots per hectare",
    },
  },
  {
    id: "park-central-towers",
    name: "Park Central Towers",
    images: [
      { src: "/images/pct1.webp", alt: "park-central-towers" },
      { src: "/images/pct2.webp", alt: "park-central-towers" },
      { src: "/images/pct3.webp", alt: "park-central-towers" },
      { src: "/images/pct4.webp", alt: "park-central-towers" },
      { src: "/images/pct5.webp", alt: "park-central-towers" },
      { src: "/images/pct6.webp", alt: "park-central-towers" },
      { src: "/images/pct7.webp", alt: "park-central-towers" },
      { src: "/images/pct8.webp", alt: "park-central-towers" },
      { src: "/images/pct9.webp", alt: "park-central-towers" },
      { src: "/images/pct10.webp", alt: "park-central-towers" },
    ],
    logo: "pct-logo.webp",
    title: "Park Central Towers",
    about:
      "At the core of a thriving city, Park Central Towers unfolds timeless residences in Makati’s urban oasis. An integrated locale places homes at the center of it all—paramount connectivity to the lush spaces of Ayala Triangle and proximity to premier lifestyle destinations in Ayala Center position everything within reach from all directions. Anchored by a curated spectrum of retail, dining, and service establishments, as well as dynamic workspaces at the podium level, Park Central Towers offers a unique living experience with a variety of delights and encounters. The 15,860-sqm development features shared amenities including a fully dedicated fitness center, multi-functional courts, a pool, indoor and outdoor lounges, and play areas, complementing distinctive residences with dynamic environments for unique everyday pursuits.",
    description:
      "Park Central Towers is located at the intersection of two major thoroughfares in the Makati Central Business District—Paseo de Roxas and Makati Avenue. The development is right across Ayala Triangle, guaranteeing a multiplicity of experiences.",
    map: "pct-map.webp",
    landArea: "15,860 sqm",
    peakElevation: "",
    location: "Makati City",
    developmentSummary: {
      noOfFloors: "69",
      noOfUnits: {
        southTower: "281 units",
        northTower: "259 units",
      },
      density: "4—6 units per floor",
      unitSizeRange: "138—1,635 sqm.",
    },
  },
  {
    id: "the-alcoves",
    name: " The Alcoves, Cebu",
    images: [
      { src: "/images/alc1.webp", alt: "the-alcoves" },
      { src: "/images/alc2.webp", alt: "the-alcoves" },
      { src: "/images/alc3.webp", alt: "the-alcoves" },
      { src: "/images/alc4.webp", alt: "the-alcoves" },
      { src: "/images/alc5.webp", alt: "the-alcoves" },
      { src: "/images/alc6.webp", alt: "the-alcoves" },
      { src: "/images/alc7.webp", alt: "the-alcoves" },
      { src: "/images/alc8.webp", alt: "the-alcoves" },
      { src: "/images/alc9.webp", alt: "the-alcoves" },
      { src: "/images/alc10.webp", alt: "the-alcoves" },
    ],
    logo: "alc-logo.webp",
    title: "The Alcoves",
    about:
      "Surrounding you with the finest elements for living, Ayala Land Premier’s newest vertical community, The Alcoves, places you at the heart of the city’s vibrant lifestyle district. With private access to Ayala Center Cebu’s array of retail, dining, and leisure destinations, your address provides the perfect backdrop for your chosen lifestyle. Every day is inspired by an abundance of opportunities that welcome you home.",

    description:
      "Cebu Park District is located at Luzon Avenue, Cebu Business Park, Brgy. Mabolo, Cebu City. Residents of The Alcoves will have direct access to Ayala Center Cebu and enjoy retail and dining establishments at the ground, 2nd, and 3rd levels. Life abounds amidst a variety of choices, with select opportunities for leisure, dining, and retail right at your doorstep.",
    map: "alc-map.webp",
    landArea: "",
    peakElevation: "",
    location: "Cebu City",
    developmentSummary: {
      noOfFloors: "37",
      noOfUnits: "480",
      density: "4 — 10 units per floor",
      unitSizeRange: "58 — 259 sqm",
    },
  },
];
